import type { V2VariantConfig } from "./types";

export const blackTie: V2VariantConfig = {
  id: "black_tie",
  displayName: "Black Tie",
  description: "Timeless black and white with champagne gold accents",
  category: "classic",
  bestFor: ["ballroom", "formal wedding", "evening", "luxury venue"],
  fontPair: "classic",
  palette: {
    ivory: "#fafafa",
    cream: "#f5f5f5",
    linen: "#e5e5e5",
    sand: "#d4d4d4",
    stone: "#a3a3a3",
    earth: "#737373",
    charcoal: "#262626",
    night: "#0a0a0a",
    sage: "#c5a55a",
    sageLight: "#ddc07a",
    sageDark: "#9e7e3a",
    forest: "#b8942e",
    gold: "#c5a55a",
    goldLight: "#ddc07a",
    goldDark: "#9e7e3a",
    rose: "#c5a55a",
    bg: "#fafafa",
    surface: "#ffffff",
    text: "#262626",
    text2: "#525252",
    text3: "#a3a3a3",
    border: "#e5e5e5",
    accent: "#c5a55a",
    accent2: "#0a0a0a",
  },
  glass: {
    frostedBg: "rgba(250, 250, 250, 0.55)",
    frostedBgScrolled: "rgba(250, 250, 250, 0.92)",
    mobileNavBg: "rgba(250, 250, 250, 0.97)",
    heroOverlayColor: "#fafafa",
    accentTint: "rgba(197, 165, 90, 0.08)",
    accentHoverBg: "rgba(197, 165, 90, 0.06)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: false,
    footerSkyline: false,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#c5a55a", label: "Champagne" },
    { hex: "#b8942e", label: "Old Gold" },
    { hex: "#0a0a0a", label: "Black" },
    { hex: "#737373", label: "Charcoal" },
    { hex: "#ddc07a", label: "Light Gold" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #9e7e3a, #c5a55a, #ddc07a)",
};
