import type { V2VariantConfig } from "./types";

export const emeraldIvory: V2VariantConfig = {
  id: "emerald_ivory",
  displayName: "Emerald & Ivory",
  description: "Deep forest greens and warm ivory for enchanted evening celebrations",
  category: "bold",
  bestFor: ["garden evening", "enchanted forest", "botanical luxury", "autumn", "estate wedding"],
  fontPair: "playfair_dmsans",
  palette: {
    ivory: "#0a1f16",
    cream: "#122b1f",
    linen: "#1a3829",
    sand: "#2d5a42",
    stone: "#6b9a7e",
    earth: "#96bea6",
    charcoal: "#e4e8e5",
    night: "#ffffff",
    sage: "#c9b88c",
    sageLight: "#ddd0a8",
    sageDark: "#a89868",
    forest: "#c9b88c",
    gold: "#c9b88c",
    goldLight: "#ddd0a8",
    goldDark: "#a89868",
    rose: "#c9b88c",
    bg: "#0a1f16",
    surface: "#122b1f",
    text: "#e4e8e5",
    text2: "#96bea6",
    text3: "#6b9a7e",
    border: "#1a3829",
    accent: "#c9b88c",
    accent2: "#ddd0a8",
  },
  glass: {
    frostedBg: "rgba(10, 31, 22, 0.55)",
    frostedBgScrolled: "rgba(10, 31, 22, 0.92)",
    mobileNavBg: "rgba(10, 31, 22, 0.97)",
    heroOverlayColor: "#0a1f16",
    accentTint: "rgba(201, 184, 140, 0.12)",
    accentHoverBg: "rgba(201, 184, 140, 0.08)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: false,
    footerSkyline: false,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#c9b88c", label: "Warm Ivory" },
    { hex: "#ddd0a8", label: "Champagne" },
    { hex: "#a89868", label: "Antique Gold" },
    { hex: "#6b9a7e", label: "Sage Mist" },
    { hex: "#96bea6", label: "Celadon" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #a89868, #c9b88c, #ddd0a8)",
};
