import type { V2VariantConfig } from "./types";

export const lavenderMist: V2VariantConfig = {
  id: "lavender_mist",
  displayName: "Lavender Mist",
  description: "Ethereal lavender and lilac with silver accents",
  category: "romantic",
  bestFor: ["fairy-tale wedding", "spring", "pastel theme", "whimsical"],
  fontPair: "playfair_dmsans",
  palette: {
    ivory: "#f9f7fb",
    cream: "#f0ecf5",
    linen: "#e3dced",
    sand: "#d0c8dc",
    stone: "#a89cb8",
    earth: "#7d7290",
    charcoal: "#35303e",
    night: "#1a1720",
    sage: "#8b7aaa",
    sageLight: "#a99ec0",
    sageDark: "#6d5e8a",
    forest: "#5c4e78",
    gold: "#b0a8c0",
    goldLight: "#d0c8dc",
    goldDark: "#8a82a0",
    rose: "#a888b0",
    bg: "#f9f7fb",
    surface: "#fefeff",
    text: "#35303e",
    text2: "#7d7290",
    text3: "#a89cb8",
    border: "#e3dced",
    accent: "#8b7aaa",
    accent2: "#b0a8c0",
  },
  glass: {
    frostedBg: "rgba(249, 247, 251, 0.55)",
    frostedBgScrolled: "rgba(249, 247, 251, 0.92)",
    mobileNavBg: "rgba(249, 247, 251, 0.97)",
    heroOverlayColor: "#f9f7fb",
    accentTint: "rgba(139, 122, 170, 0.08)",
    accentHoverBg: "rgba(139, 122, 170, 0.06)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: false,
    footerSkyline: true,
    botanicals: true,
    botanicalVariant: "sage",
  },
  accentSwatches: [
    { hex: "#8b7aaa", label: "Lavender" },
    { hex: "#6d5e8a", label: "Violet" },
    { hex: "#a99ec0", label: "Wisteria" },
    { hex: "#9688b0", label: "Lilac" },
    { hex: "#7a6a98", label: "Amethyst" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #a99ec0, #8b7aaa, #d0c8dc)",
};
