import type { V2VariantConfig } from "./types";

export const midnightGold: V2VariantConfig = {
  id: "midnight_gold",
  displayName: "Midnight & Gold",
  description: "Dramatic navy and gold for glamorous evening celebrations",
  category: "bold",
  bestFor: ["evening wedding", "ballroom", "formal", "winter", "New Year"],
  fontPair: "playfair_dmsans",
  palette: {
    ivory: "#0d1b2a",
    cream: "#1b2838",
    linen: "#243447",
    sand: "#3d5a80",
    stone: "#8da9c4",
    earth: "#b0c4de",
    charcoal: "#e8e8e8",
    night: "#ffffff",
    sage: "#c5a55a",
    sageLight: "#ddc07a",
    sageDark: "#9e7e3a",
    forest: "#c5a55a",
    gold: "#c5a55a",
    goldLight: "#ddc07a",
    goldDark: "#9e7e3a",
    rose: "#c5a55a",
    bg: "#0d1b2a",
    surface: "#1b2838",
    text: "#e8e8e8",
    text2: "#b0c4de",
    text3: "#8da9c4",
    border: "#243447",
    accent: "#c5a55a",
    accent2: "#ddc07a",
  },
  glass: {
    frostedBg: "rgba(13, 27, 42, 0.55)",
    frostedBgScrolled: "rgba(13, 27, 42, 0.92)",
    mobileNavBg: "rgba(13, 27, 42, 0.97)",
    heroOverlayColor: "#0d1b2a",
    accentTint: "rgba(197, 165, 90, 0.12)",
    accentHoverBg: "rgba(197, 165, 90, 0.08)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: false,
    footerSkyline: false,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#c5a55a", label: "Gold" },
    { hex: "#ddc07a", label: "Champagne" },
    { hex: "#9e7e3a", label: "Antique Gold" },
    { hex: "#8da9c4", label: "Steel Blue" },
    { hex: "#e8d5b7", label: "Ivory Gold" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #9e7e3a, #c5a55a, #ddc07a)",
  thumbnail: "/variants/midnight_gold-thumb.jpg",
};
