import type { V2VariantConfig } from "./types";

export const plumBlush: V2VariantConfig = {
  id: "plum_blush",
  displayName: "Plum & Blush",
  description: "Rich plum depths with dusty rose accents for romantic evening affairs",
  category: "bold",
  bestFor: ["romantic evening", "wine country", "autumn harvest", "vineyard", "intimate dinner"],
  fontPair: "playfair_dmsans",
  palette: {
    ivory: "#1a0f1e",
    cream: "#251828",
    linen: "#322236",
    sand: "#4e3856",
    stone: "#8a6e90",
    earth: "#b098b6",
    charcoal: "#e8e2ea",
    night: "#ffffff",
    sage: "#d4a0a0",
    sageLight: "#e4baba",
    sageDark: "#b87878",
    forest: "#d4a0a0",
    gold: "#d4a0a0",
    goldLight: "#e4baba",
    goldDark: "#b87878",
    rose: "#d4a0a0",
    bg: "#1a0f1e",
    surface: "#251828",
    text: "#e8e2ea",
    text2: "#b098b6",
    text3: "#8a6e90",
    border: "#322236",
    accent: "#d4a0a0",
    accent2: "#e4baba",
  },
  glass: {
    frostedBg: "rgba(26, 15, 30, 0.55)",
    frostedBgScrolled: "rgba(26, 15, 30, 0.92)",
    mobileNavBg: "rgba(26, 15, 30, 0.97)",
    heroOverlayColor: "#1a0f1e",
    accentTint: "rgba(212, 160, 160, 0.12)",
    accentHoverBg: "rgba(212, 160, 160, 0.08)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: false,
    footerSkyline: false,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#d4a0a0", label: "Dusty Rose" },
    { hex: "#e4baba", label: "Blush" },
    { hex: "#b87878", label: "Rosewood" },
    { hex: "#8a6e90", label: "Lavender Mist" },
    { hex: "#c8b0a0", label: "Warm Sand" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #b87878, #d4a0a0, #e4baba)",
};
