import type { V2VariantConfig } from "./types";

export const scrapbookEdition: V2VariantConfig = {
  id: "scrapbook_edition",
  displayName: "Scrapbook Edition",
  description: "Playful polaroid gallery and flip-card bridal party on warm cream",
  category: "romantic",
  bestFor: [
    "family weddings",
    "multicultural celebrations",
    "casual weddings",
    "photo-rich events",
  ],
  fontPair: "dmsans_sourceserif",
  palette: {
    ivory: "#faf7f2",
    cream: "#f2ece4",
    linen: "#e6ddd2",
    sand: "#d2c6b6",
    stone: "#a09488",
    earth: "#746860",
    charcoal: "#38302c",
    night: "#1c1816",
    sage: "#8a7e6e",
    sageLight: "#b0a494",
    sageDark: "#6a5e4e",
    forest: "#5c5244",
    gold: "#c4a86c",
    goldLight: "#dcc48c",
    goldDark: "#a08848",
    rose: "#c09080",
    bg: "#faf7f2",
    surface: "#ffffff",
    text: "#38302c",
    text2: "#746860",
    text3: "#a09488",
    border: "#e6ddd2",
    accent: "#8a7e6e",
    accent2: "#c4a86c",
  },
  glass: {
    frostedBg: "rgba(250, 247, 242, 0.55)",
    frostedBgScrolled: "rgba(250, 247, 242, 0.95)",
    mobileNavBg: "rgba(250, 247, 242, 0.97)",
    heroOverlayColor: "#faf7f2",
    accentTint: "rgba(138, 126, 110, 0.08)",
    accentHoverBg: "rgba(138, 126, 110, 0.05)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: true,
    footerSkyline: true,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#8a7e6e", label: "Warm Stone" },
    { hex: "#c4a86c", label: "Honey Gold" },
    { hex: "#c09080", label: "Dusty Rose" },
    { hex: "#7a8c72", label: "Sage" },
    { hex: "#6a5e4e", label: "Espresso" },
  ],
  galleryRenderer: "scrapbook",
  weddingPartyRenderer: "scrapbook",
};
