import type { V2VariantConfig } from "./types";

export const scrapbookEmerald: V2VariantConfig = {
  id: "scrapbook_emerald",
  displayName: "Emerald Scrapbook",
  family: "scrapbook",
  description: "Polaroid gallery and flip-card party on deep forest greens",
  category: "bold",
  bestFor: [
    "garden evening",
    "enchanted forest",
    "estate wedding",
    "autumn",
    "photo-rich celebration",
  ],
  fontPair: "dmsans_sourceserif",
  palette: {
    // Page-level dark neutrals (V2 default sections render against these)
    bg: "#0a1f16",
    ivory: "#0a1f16",
    cream: "#122b1f",
    linen: "#1a3829",
    sand: "#2d5a42",
    border: "#16321f",
    // Page-level light text neutrals (topbar, section titles, body)
    text: "#f1ede5",
    text2: "#96bea6",
    text3: "#6b9a7e",
    stone: "#6b9a7e",
    earth: "#96bea6",
    charcoal: "#f1ede5",
    night: "#ffffff",
    // Polaroid card surface (Scrapbook renderers only)
    surface: "#fbf9f4",
    // On-card overrides — dark text on cream polaroid + cream back face
    textOnCard: "#2a2820",
    text2OnCard: "#5a564a",
    stoneOnCard: "#a39c8a",
    creamOnCard: "#f1ede5",
    // Accent family — warm ivory gold (works on both emerald bg and cream surface)
    accent: "#c9b88c",
    accent2: "#ddd0a8",
    gold: "#c9b88c",
    goldLight: "#ddd0a8",
    goldDark: "#a89868",
    sage: "#c9b88c",
    sageLight: "#ddd0a8",
    sageDark: "#a89868",
    forest: "#c9b88c",
    rose: "#c9b88c",
  },
  glass: {
    frostedBg: "rgba(10, 31, 22, 0.55)",
    frostedBgScrolled: "rgba(10, 31, 22, 0.92)",
    mobileNavBg: "rgba(10, 31, 22, 0.97)",
    heroOverlayColor: "#0a1f16",
    accentTint: "rgba(201, 184, 140, 0.12)",
    accentHoverBg: "rgba(201, 184, 140, 0.08)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: true,
    footerSkyline: true,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#c9b88c", label: "Warm Ivory" },
    { hex: "#ddd0a8", label: "Champagne" },
    { hex: "#a89868", label: "Antique Gold" },
    { hex: "#6b9a7e", label: "Sage Mist" },
    { hex: "#96bea6", label: "Celadon" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #a89868, #c9b88c, #ddd0a8)",
  galleryRenderer: "scrapbook",
  weddingPartyRenderer: "scrapbook",
  heroImageTip:
    "This variant works best with a dark or moody hero image — bright photos can clash with the deep forest page and reduce contrast on overlay text.",
};
