import type { V2VariantConfig } from "./types";

export const scrapbookMidnight: V2VariantConfig = {
  id: "scrapbook_midnight",
  displayName: "Midnight Scrapbook",
  family: "scrapbook",
  description: "Polaroid gallery and flip-card party on a deep midnight navy page",
  category: "bold",
  bestFor: [
    "evening wedding",
    "ballroom",
    "formal photo-rich event",
    "winter",
    "New Year",
  ],
  fontPair: "dmsans_sourceserif",
  palette: {
    // Page-level dark neutrals (V2 default sections render against these)
    bg: "#0d1b2a",
    ivory: "#0d1b2a",
    cream: "#1b2838",
    linen: "#243447",
    sand: "#3d5a80",
    border: "#1a2940",
    // Page-level light text neutrals (topbar, section titles, body)
    text: "#f1ece2",
    text2: "#b0c4de",
    text3: "#8da9c4",
    stone: "#8da9c4",
    earth: "#b0c4de",
    charcoal: "#f1ece2",
    night: "#ffffff",
    // Polaroid card surface (Scrapbook renderers only)
    surface: "#fbf8f3",
    // On-card overrides — dark text on cream polaroid + cream back face
    textOnCard: "#2a2622",
    text2OnCard: "#5a544c",
    stoneOnCard: "#a39a8e",
    creamOnCard: "#f1ece2",
    // Accent family — champagne gold (works on both navy bg and cream surface)
    accent: "#c5a55a",
    accent2: "#ddc07a",
    gold: "#c5a55a",
    goldLight: "#ddc07a",
    goldDark: "#9e7e3a",
    sage: "#c5a55a",
    sageLight: "#ddc07a",
    sageDark: "#9e7e3a",
    forest: "#c5a55a",
    rose: "#c5a55a",
  },
  glass: {
    frostedBg: "rgba(13, 27, 42, 0.55)",
    frostedBgScrolled: "rgba(13, 27, 42, 0.92)",
    mobileNavBg: "rgba(13, 27, 42, 0.97)",
    heroOverlayColor: "#0d1b2a",
    accentTint: "rgba(197, 165, 90, 0.12)",
    accentHoverBg: "rgba(197, 165, 90, 0.08)",
  },
  chromeDefaults: {
    topbar: true,
    scrollProgress: true,
    mountainDividers: true,
    footerSkyline: true,
    botanicals: false,
    botanicalVariant: "none",
  },
  accentSwatches: [
    { hex: "#c5a55a", label: "Gold" },
    { hex: "#ddc07a", label: "Champagne" },
    { hex: "#9e7e3a", label: "Antique Gold" },
    { hex: "#8da9c4", label: "Steel Blue" },
    { hex: "#e8d5b7", label: "Ivory Gold" },
  ],
  scrollProgressGradient: "linear-gradient(90deg, #9e7e3a, #c5a55a, #ddc07a)",
  galleryRenderer: "scrapbook",
  weddingPartyRenderer: "scrapbook",
  heroImageTip:
    "This variant works best with a dark or moody hero image — bright photos can clash with the deep navy page and reduce contrast on overlay text.",
};
